package mime

var mapMimeToExt = map[string]string{
	// Text files
	"text/plain":              ".txt",
	"text/html":               ".html",
	"text/css":                ".css",
	"text/csv":                ".csv",
	"text/xml":                ".xml",
	"text/javascript":         ".mjs",
	"text/markdown":           ".md",
	"text/yaml":               ".yaml",
	"text/jsx":                ".jsx",
	"text/tsx":                ".tsx",
	"text/n3":                 ".n3",
	"text/turtle":             ".ttl",
	"text/sgml":               ".sgml",
	"text/x-setext":           ".etx",
	"text/vnd.fly":            ".fly",
	"text/plain-bas":          ".par",
	"text/uri-list":           ".uri",
	"text/x-vcalendar":        ".vcs",
	"text/vnd.wap.wml":        ".wml",
	"text/x-asm":              ".s",
	"text/x-c":                ".c",
	"text/x-fortran":          ".f",
	"text/x-java-source,java": ".java",
	"text/x-pascal":           ".p",
	"text/x-python":           ".py",
	"text/x-ruby":             ".rb",
	"text/x-uuencode":         ".uu",
	"text/x-vcard":            ".vcf",

	// Image files
	"image/jpeg":                ".jpg",
	"image/png":                 ".png",
	"image/gif":                 ".gif",
	"image/bmp":                 ".bmp",
	"image/webp":                ".webp",
	"image/svg+xml":             ".svg",
	"image/x-icon":              ".ico",
	"image/tiff":                ".tiff",
	"image/x-raw":               ".raw",
	"image/vnd.adobe.photoshop": ".psd",
	"image/ktx":                 ".ktx",
	"image/vnd.dwg":             ".dwg",
	"image/vnd.dxf":             ".dxf",
	"image/vnd.fst":             ".fst",
	"image/vnd.fastbidsheet":    ".fbs",
	"image/vnd.fpx":             ".fpx",
	"image/vnd.net-fpx":         ".npx",
	"image/vnd.wap.wbmp":        ".wbmp",
	"image/vnd.xiff":            ".xif",
	"image/x-macpaint":          ".mac",
	"image/x-pict":              ".pic",
	"image/x-portable-anymap":   ".pnm",
	"image/x-portable-bitmap":   ".pbm",
	"image/x-portable-graymap":  ".pgm",
	"image/x-portable-pixmap":   ".ppm",
	"image/x-rgb":               ".rgb",
	"image/x-xbitmap":           ".xbm",
	"image/x-xpixmap":           ".xpm",
	"image/x-xwindowdump":       ".xwd",

	// Audio files
	"audio/mpeg":              ".mp3",
	"audio/wav":               ".wav",
	"audio/ogg":               ".ogg",
	"audio/mp4":               ".m4a",
	"audio/midi":              ".midi",
	"audio/aac":               ".aac",
	"audio/x-ms-wma":          ".wma",
	"audio/x-realaudio":       ".ra",
	"audio/flac":              ".flac",
	"audio/adpcm":             ".adp",
	"audio/basic":             ".au",
	"audio/vnd.digital-winds": ".eol",
	"audio/vnd.dra":           ".dra",
	"audio/vnd.dts":           ".dts",
	"audio/vnd.dts.hd":        ".dtshd",
	"audio/vnd.lucent.voice":  ".lvp",
	"audio/x-aiff":            ".aif",
	"audio/x-mpegurl":         ".m3u",
	"audio/x-pn-realaudio":    ".ram",

	// Video files
	"video/mp4":         ".mp4",
	"video/webm":        ".webm",
	"video/x-msvideo":   ".avi",
	"video/quicktime":   ".mov",
	"video/x-matroska":  ".mkv",
	"video/x-ms-wmv":    ".wmv",
	"video/x-flv":       ".flv",
	"video/3gpp":        ".3gp",
	"video/x-m4v":       ".m4v",
	"video/mpeg":        ".mpg",
	"video/3gpp2":       ".3g2",
	"video/h261":        ".h261",
	"video/h263":        ".h263",
	"video/h264":        ".h264",
	"video/jpeg":        ".jpgv",
	"video/jpm":         ".jpm",
	"video/mj2":         ".mj2",
	"video/ogg":         ".ogv",
	"video/vnd.vivo":    ".viv",
	"video/x-f4v":       ".f4v",
	"video/x-fli":       ".fli",
	"video/x-sgi-movie": ".movie",

	// Application files
	"application/json":   ".json",
	"application/pdf":    ".pdf",
	"application/msword": ".doc",
	"application/vnd.openxmlformats-officedocument.wordprocessingml.document": ".docx",
	"application/vnd.ms-excel": ".xls",
	"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":         ".xlsx",
	"application/vnd.ms-powerpoint":                                             ".ppt",
	"application/vnd.openxmlformats-officedocument.presentationml.presentation": ".pptx",
	"application/zip":                                 ".zip",
	"application/gzip":                                ".gz",
	"application/x-tar":                               ".tar",
	"application/x-7z-compressed":                     ".7z",
	"application/javascript":                          ".js",
	"application/wasm":                                ".wasm",
	"application/rtf":                                 ".rtf",
	"application/typescript":                          ".ts",
	"application/postscript":                          ".ai",
	"application/vnd.oasis.opendocument.text":         ".odt",
	"application/vnd.oasis.opendocument.spreadsheet":  ".ods",
	"application/vnd.oasis.opendocument.presentation": ".odp",
	"application/epub+zip":                            ".epub",
	"application/x-tex":                               ".tex",
	"application/x-latex":                             ".latex",
	"application/vnd.rar":                             ".rar",
	"application/x-bzip":                              ".bz",
	"application/x-bzip2":                             ".bz2",
	"application/vnd.ms-cab-compressed":               ".cab",
	"application/x-iso9660-image":                     ".iso",
	"application/x-shockwave-flash":                   ".swf",
	"application/java-archive":                        ".jar",
	"application/x-httpd-php":                         ".php",
	"application/x-sh":                                ".sh",
	"application/sql":                                 ".sql",
	"application/vnd.android.package-archive":         ".apk",
	"application/x-msdownload":                        ".exe",
	"application/x-debian-package":                    ".deb",
	"application/x-rpm":                               ".rpm",
	"application/vnd.ms-fontobject":                   ".eot",
	"application/x-matlab-data":                       ".mat",
	"application/mathematica":                         ".nb",
	"application/yang":                                ".yang",
	"application/yin+xml":                             ".yin",

	// Font files
	"font/ttf":   ".ttf",
	"font/otf":   ".otf",
	"font/woff":  ".woff",
	"font/woff2": ".woff2",

	// Message files
	"message/rfc822": ".eml",

	// Model files
	"model/stl":     ".stl",
	"model/obj":     ".obj",
	"model/vnd.mts": ".mts",
	"model/vnd.vtu": ".vtu",
	"model/vrml":    ".wrl",
	"model/iges":    ".iges",
	"model/mesh":    ".mesh",
	"model/vnd.dwf": ".dwf",
	"model/vnd.gdl": ".gdl",
	"model/vnd.gtw": ".gtw",

	// Chemical files
	"chemical/x-xyz":  ".xyz",
	"chemical/x-cdx":  ".cdx",
	"chemical/x-cif":  ".cif",
	"chemical/x-cmdf": ".cmdf",
	"chemical/x-cml":  ".cml",
	"chemical/x-csml": ".csml",
}
